version: "3.7"
services:

  db:
    container_name: db_postgres
    image: postgres
    env_file: ./.enviroments/.dev
    volumes:
      - db:/var/lib/postgresql/data

  api:
    container_name: api_rails
    env_file: ./.enviroments/.dev
    build: ./api
    command: bash -c "rm -f /api/tmp/pids/server.pid && rake db:create && rake db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/api
      - rails_log:/api/log
    ports:
      - "3000:3000"
    depends_on:
      - db

  client:
    container_name: client_front
    build: ./client
    ports:
      - "8080:8080"
    volumes:
      - ./client:/client
      - client_node_modules:/client/node_modules

volumes:
  db:
  rails_log:
  client_node_modules:
