
name: CI

on:
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master
    - release/*
    - develop

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        ports: ["5491:5432"]
        env:
          POSTGRES_PASSWORD: password
           
    steps:
    - uses: actions/checkout@master
    - name: Build environment
      run: docker-compose up -d --build
    - name: Install PostgreSQL 12 client
      run: |
        sudo apt-get -yqq install libpq-dev
    - name: Bundle Install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Run Tests
      env:
        PG_DATABASE: postgres
        PG_HOST: db
        PG_USER: postgres
        PG_PASSWORD: password
        RAILS_ENV: test
        WITH_COVERAGE: true
        DISABLE_SPRING: 1
      run: |
        bin/rails db:setup
        bundle exec rake test
