
name: CI

on:
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master
    - release/*
    - develop

jobs:
  ci:

    runs-on: ubuntu-latest
           
    steps:
    - uses: actions/checkout@master
    - name: Build environment
      run: docker-compose up -d --build
      
    - name: Prepare database environment
      run: docker-compose run api rake db:create
    
    - name: Run migrations
      run: docker-compose run api rake db:migrate
     
    - name: Run Tests
      run: docker-compose run api bundle exec rails test
